id: P84E34897
initial_creation_type: input
source_metadata:
  title: Lobzang Chökyi Gyaltsen
  language: bo
  description: 'Texts by and about Lobzang Chökyi Gyaltsen (blo bzang chos kyi rgyal
    mtshan, 1570–1662), the first or fourth Paṇchen Lama (depending on the method
    of counting), a prolific author and teacher of the Fifth Dalai Lama:'
  volume:
    0f1842f17b454bab86685b73a855c45b:
      title: A Method of Confessing and Pledging through the Four Powers
      parent: Confession
    f2f3c58e16af4557b2c428172bd7e7a7:
      title: Method of Confession based on the Four Powers
      parent: Confession
    ab7e634f7fa94e7d90085ce6269d7ed2:
      title: Rays of Moonlight to Dispel the Darkness of Misdeeds
      parent: Confession
    345290aa870d4d838f0fd31fa3de7c21:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Offering Rites
created_at: '2022-03-01T00:37:38.008350'
last_modified_at: '2022-03-01T00:37:38.008353'
statistics:
  total_words: 4501
  total_non_words: 582
quality:
  non_words_ratio: 0.13
